[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:hbbs]
command=/usr/bin/hbbs -r 0.0.0.0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:hbbr]
command=/usr/bin/hbbr
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
